### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by EdsonAlcala** [EdsonAlcala/quorum-n-nodes#1]
- [x] Include privacy feature with Tessera
- [ ] Make the number of nodes dynamic
- [x] Fix the problem that stops the container after it starts
- [ ] Make abstraction to allow run just 1 node per container and think about how to integrate with Minikube
